name: plant_disease_doctor
description: A Flutter client for diagnosing plant diseases using an existing API.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  image_picker: ^1.0.4
  flutter_spinkit: ^5.2.0

flutter:
  uses-material-design: true
